# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
